Enabled:
  NoContainers:
    approved_images: ['ubuntu-latest']
  SpecialPermissions:
  EmptyName:
  RiskyTriggers:
  UnapprovedRunners:
    allowed_runners: ["ubuntu-latest", "macos-12"]
  CommandInjection:
  AutomaticMerge:
  UnpinnedAction:
    trusted_authors: ["Betterment"]
    loose_validation: false
  UnsafeCheckout:
  InheritedSecrets:
  BulkPermissions:
