on: pull_request

name: Specs Exist

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Ensure Each Rule has a Spec
        run: |
          # shellcheck disable=SC2012,SC2046
          ls $(for spec in $(ls lib/claws/rule/ | sed 's/\.rb/_spec\.rb/g'); do echo "spec/claws/rule/$spec"; done) >/dev/null
